name: sphinx

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["docs/**"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version:
      - run: bash .tools/scripts/cicd_setup.sh
      - run: python -m sphinx -T -E docs _site
      - uses: actions/upload-pages-artifact@v1
  deploy:
    environment:
      name: github-pages
      url: "{% raw %}${{ steps.deployment.outputs.page_url }}{% endraw %}"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
