# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.1.1-135-g0ec9b4e
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-22.04
active: true
github_repo_name: copier-python
project_description: Copier template for Python projects
project_email: blake.naccarato@gmail.com
project_name: copier_python
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
project_version: 2024.1.1
python_version: '3.10'
year_of_project_creation: 2022
