blank_issues_enabled: false
contact_links:
  - name: "Ask a question"
    url: "https://github.com/blakeNaccarato/copier-python/discussions/new?category=q-a"
    about: "Ask for help. In case your question has been asked before, for quicker results you can search existing Discussion Q&As."
