[build-system]
requires = ["flit_core==3.9.0"]
build-backend = "flit_core.buildapi"

[project]
name = "copier_python_tools"
version = "0.0.0"
description = "Tools."
dependencies = [
    "copier==9.1.1",
    "cyclopts==2.4.2",
    "pre-commit==3.6.2",
    "zstandard==0.22.0",
]
[project.scripts]
copier_python_tools = "copier_python_tools.__main__:main"

[tool.fawltydeps]
actions = ["check_undeclared"]
deps = ["scripts/pyproject.toml", "pyproject.toml"]
code = ["scripts/copier_python_tools"]
