[build-system]
requires = ["flit_core==3.9.0"]
build-backend = "flit_core.buildapi"

[project]
name = "copier_python_tools"
version = "0.0.0"
description = "Tools."
dependencies = ["cyclopts==2.5.0"]
[project.scripts]
"copier_python_tools" = "copier_python_tools.__main__:main"

[tool.fawltydeps]
deps = ["scripts/pyproject.toml", "pyproject.toml"]
code = ["scripts/copier_python_tools"]
ignore_undeclared = [
    "copier_python",
    "copier_python_docs",
    "copier_python_scripts",
    "copier_python_tests",
]
