name: bump

on:
  push:
    branches: [main]
    paths: ["dependabot/**"]

jobs:
  bump:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - run: python dependabot/bump.py
      - uses: stefanzweifel/git-auto-commit-action@v4.12.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          commit_message: Bump dependencies
