name: bump_workflows

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [bump/workflows/*]

jobs:
  bump:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python bump/workflows.py
      - uses: stefanzweifel/git-auto-commit-action@v4.15.3
        with:
          commit_message: Bump dependencies
