name: bump

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths: ["dependabot/**"]

jobs:
  bump:
    runs-on: ubuntu-20.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - run: python dependabot/bump.py
      - uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: Bump dependencies
