# Publish release
name: "release"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: True
on:
  release:
    types: ["published"]
defaults:
  run:
    shell: "pwsh"
jobs:
  release:
    permissions:
      contents: "write"
      id-token: "write"
      attestations: "write"
    runs-on: "ubuntu-22.04"
    environment:
      name: "release"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
      - uses: "astral-sh/setup-uv@abac0ce7b0768476333db78faaf98b1130f5face" # v3.1.1
        with:
          version: "0.4.15"
          enable-cache: true
          cache-dependency-glob: |
            **/uv.lock
            .github/workflows/**
      - run: "./Invoke-Uv.ps1 -Build"
      - uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
        with:
          subject-path: "dist/**"
  changerelease:
    needs: "release"
    permissions:
      contents: "write"
    uses: "./.github/workflows/changerelease.yml"
